from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Protocol
from models.specs import LinkSpec, PageSpec, RenderManifest

class CanvasLike(Protocol):
    def saveState(self) -> None: ...
    def restoreState(self) -> None: ...
    def showPage(self) -> None: ...
    def bookmarkPage(self, name: str, *args, **kwargs) -> None: ...
    def linkAbsolute(self, contents: str, destinationname: str, Rect: tuple[float, float, float, float], **kwargs) -> None: ...

class PageRenderer(ABC):
    template_id: str
    @abstractmethod
    def render(self, canvas: CanvasLike, page: PageSpec, manifest: RenderManifest) -> None: ...

class HyperlinkRenderer(ABC):
    @abstractmethod
    def register_page_bookmark(self, canvas: CanvasLike, page: PageSpec) -> None: ...
    @abstractmethod
    def register_link(self, canvas: CanvasLike, link: LinkSpec) -> None: ...
